Repository webpack-contrib/extract-text-webpack-plugin, pull requests merged in 2018-03, with the labels that each got.

#746 fix(index): remove empty assets
  package-lock.json
  package.json
  src/index.js
  test/__snapshots__/webpack-integration.test.js.snap
  test/cases/empty-chunk/a.js
  test/cases/empty-chunk/a.txt
  test/cases/empty-chunk/b.js
  test/cases/empty-chunk/b.txt
  test/cases/empty-chunk/c.txt
  test/cases/empty-chunk/expected/main.css
  test/cases/empty-chunk/index.js
  test/cases/empty-chunk/webpack.config.js
  test/webpack-integration.test.js
Labels: semver: Patch, status: Approved, type: Bug

#687 fix(index): handle `module` extraction correctly (`require.ensure`)
  src/index.js
  test/__snapshots__/webpack-integration.test.js.snap
  test/cases/splitted-mix-multiple-entries/a.js
  test/cases/splitted-mix-multiple-entries/a.txt
  test/cases/splitted-mix-multiple-entries/b.js
  test/cases/splitted-mix-multiple-entries/b.txt
  test/cases/splitted-mix-multiple-entries/c.js
  test/cases/splitted-mix-multiple-entries/c.txt
  test/cases/splitted-mix-multiple-entries/expected/a.txt
  test/cases/splitted-mix-multiple-entries/expected/b.txt
  test/cases/splitted-mix-multiple-entries/webpack.config.js
Labels: semver: Patch, status: Approved, type: Bug

#725 perf(index): use `neo-async` instead `async`
  package-lock.json
  package.json
  src/index.js
Labels: semver: Patch, status: Approved, type: Perf

#709 test(cases): hashed module ids
  test/__snapshots__/webpack-integration.test.js.snap
  test/cases/hashed-module-ids/a.js
  test/cases/hashed-module-ids/a.txt
  test/cases/hashed-module-ids/b.js
  test/cases/hashed-module-ids/b.txt
  test/cases/hashed-module-ids/expected/main.txt
  test/cases/hashed-module-ids/index.js
  test/cases/hashed-module-ids/index.txt
  test/cases/hashed-module-ids/webpack.config.js
Labels: semver: Patch, status: Approved, type: Test
